### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by willtownes** [PMBio/scLVM#3]
Tried installing with pip and got the following error, any suggestions?

```
Using cached scLVM-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/_r/b9d9b51x4c7dkxfv5m74bwsw0000gn/T/pip-build-UVqiVd/sclvm/setup.py", line 16, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/_r/b9d9b51x4c7dkxfv5m74bwsw0000gn/T/pip-build-UVqiVd/sclvm/README.md'
```

**Comment by chenhao392** [comment]
I got the same error earlier today. 
You can manually install the package after renaming file "README" to "README.md".

**Comment by flophys** [comment]
Sorry for this. Fixed now and pip install should work again.

**Comment by willtownes** [comment]
thanks, it seems to be working for me now.
